# Generated by Django 2.2.5 on 2019-10-30 00:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FoodCourt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('fc_id', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=50)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='pics/')),
                ('rating', models.FloatField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodapp.Category')),
                ('foodcourt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodapp.FoodCourt')),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField(default=0)),
                ('empid', models.IntegerField(default=0)),
                ('dob', models.DateField(null=True)),
                ('user_type', models.CharField(choices=[(1, 'Store Manager'), (2, 'User')], default=2, max_length=100)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MenuCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.CharField(max_length=100)),
                ('store', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='foodapp.Store')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField(default=0)),
                ('cuisine', models.CharField(max_length=100)),
                ('is_available', models.BooleanField(default=True)),
                ('description', models.TextField(max_length=200)),
                ('rating', models.FloatField(default=0)),
                ('menu', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='foodapp.MenuCatalog')),
                ('store', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='foodapp.Store')),
            ],
        ),
    ]
