# Generated by Django 2.2.5 on 2019-11-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcourt',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='foodcourt-images/'),
        ),
    ]
