# Generated by Django 2.2.5 on 2019-11-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0002_foodcourt_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodcourt',
            old_name='image',
            new_name='foodcourt_image',
        ),
        migrations.AlterField(
            model_name='foodcourt',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
