# Generated by Django 2.2.5 on 2019-11-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0003_auto_20191102_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcourt',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='foodcourt',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
