# Generated by Django 2.2.5 on 2019-11-03 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0005_auto_20191103_1000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='shot_size',
            new_name='food_type',
        ),
    ]
