# Generated by Django 2.2.5 on 2019-11-03 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0006_auto_20191103_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='food_type',
        ),
    ]
