# Generated by Django 2.2.5 on 2019-11-03 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0009_item_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
    ]
